goodnight:
  alias: Goodnight
  sequence:
    - action: light.turn_off
      target:
        entity_id: light.all_lights
      data:
        transition: 2
    - action: scene.turn_on
      target:
        entity_id:
          - scene.bedroom_bedroom_nightlight
          - scene.living_room_living_room_nightlight
          - scene.juliens_bedroom_juliens_bedroom_nightlight
          - scene.mias_bedroom_mias_bedroom_nightlight
          - scene.playground_playground_nightlight
          - scene.bens_office_bens_office_nightlight
      data:
        transition: 2
